ParkourVolume = (50, 50, 50)
Difficulty = 0.5
Flow = 0.5
ParkourType = "UpwardSpiral"
BlockType = "minecraft:bedrock"
FillParkourVolumeWithAirFirst = True
StartBlockSize = (3, 3)
FinishBlockSize = (3, 3)
Stages = 1