ParkourVolume = (100, 100, 100)
MaxParkourLength = 10
Difficulty = 1.0
Flow = 0.0
ParkourType = "UpwardSpiral"
BlockType = "minecraft:bedrock"
FillParkourVolumeWithAirFirst = True
StartBlockSize = (3, 3)
FinishBlockSize = (3, 3)
Stages = 1